apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/Java
  type: core.Directory
---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: Environments/Dev
  type: core.Directory
