---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- directory: Infrastructure/AsCode
  children:
  - name: host-vm
    type: overthere.SshHost
    os: UNIX
    address: deployit.vm
    username: ubuntu
    password: ubuntu
    children:
    - name: tomcat
      type: tomcat.Server
      home: /home/ubuntu/tomcat/tomcat-as-code
      startCommand: nohup /home/ubuntu/tomcat/tomcat-as-code/bin/startup.sh && sleep 5
      stopCommand: /home/ubuntu/tomcat/tomcat-as-code/bin/shutdown.sh && sleep 5
      children:
        - name: tomcat.vh
          type: tomcat.VirtualHost
    - name: sql-db
      type: sql.PostgreSqlClient
      username: scott
      password: tiger
      databaseName: petclinicDev
      postgreSqlHome: /usr
    - name: testRunner
      type: smoketest.Runner
