apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/Java/PetPortal
  type: udm.Application
  children:
    - name: !value appversion
      type: udm.DeploymentPackage
      orchestrator:
      - sequential-by-dependency
      applicationDependencies:
         pet-service: '[1.0.0,2.0.0)'
         dog-service: '[1.0.0,2.0.0)'
         cat-service: '[1.0.0,2.0.0)'
      children:
      - name: pet.configuration
        type: k8s.ConfigMapSpec
        configMapName: petconfig
        propertyFiles:
        - name: log4j.properties
          type: k8s.ConfigMapFileSpec
          file: !file "pet.configuration/log4j.properties/log4j.properties"
        - name: petclinic.properties
          type: k8s.ConfigMapFileSpec
          file: !file "pet.configuration/petclinic.properties/petclinic.properties"
      - name: petclinic-deployment
        type: k8s.ResourcesFile
        file: !file "k8s/deployment.json"
      - name: petclinic-ingress
        type: k8s.ResourcesFile
        file: !file "k8s/ingress.json"
      - name: petclinic.service
        type: k8s.ServiceSpec
        serviceName: petclinicservice
        serviceType: LoadBalancer
        selectors:
          app: pet
        ports:
        - name: web
          type: k8s.ServicePortSpec
          port: "8080"
          targetPort: "8080"
      - name: smoke test petclinic ui
        type: smoketest.HttpRequestTest
        url: '{{smoke.test.url}}'
        expectedResponseText: '{{title}}'


